version: '3.1'
services:
  db_test:
    image: postgres:13
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=gradebook
    restart: always
    env_file:
      - ../.env
    ports:
      - "${DB_PORT:-5432}:5432"